Repository crescentpartha/CheatSheets-for-Developers, pull requests merged in 2022-10, with the labels that each got.

#9 Update git-cheatsheet.md
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest-2022, modify-needed

#15 added cheatsheet in node cheatsheet
  CheatSheets/npm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#16 Added Some NPM Commands in Npm cheatsheet
  CheatSheets/npm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#18 Added some git commands in git cheatsheets
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, review-pull-request

#22 added 2 new npm commands
  CheatSheets/npm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, review-pull-request

#20 Cmd
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, review-pull-request

#25 Hacktoberfest 2022 - Updated NPM cheat sheet
  CheatSheets/npm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, review-pull-request, ready-to-merge

#28 Hacktoberfest 2022 - Added my Node Version Manager cheat sheet
  CheatSheets/nvm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request

#30 Hacktoberfest 2022 - Added new things to the NVM Cheat sheet
  CheatSheets/nvm-cheatsheet.md
Labels: documentation, hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#31 Update nvm-cheatsheet.md
  CheatSheets/nvm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request

#34 Add windows-cheatsheet.md file for Windows Keyboard Shortcuts - resolve issue #33
  CheatSheets/git-cheatsheet.md
  CheatSheets/nvm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#36 Add vscode-cheatsheet.md file for VSCode Keyboard Shortcuts - resolve or fixes issue no #35
  CheatSheets/vscode-cheatsheet.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-2022, 📝review-pull-request

#38 Add a chrome-devtools-cheatsheet.md file for Chrome DevTools Keyboard Shortcuts - resolved issue no #37
  CheatSheets/chrome-devtools-cheatsheet.md
  README.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#32 adding cheatsheets of TEMPORARY COMMITS
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#42 Added command for task manager
  CheatSheets/git-cheatsheet.md
  CheatSheets/windows-cheatsheet.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#50 updated the windows.md
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#45 Added contents in VScode Cheat Sheet
  CheatSheets/vscode-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#46 Added commands for Yarn
  CheatSheets/yarn-cheatsheet.md
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#48 Adding cheatsheets of Inspection & Comparison
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#56 Chore: added more npm cheat sheet
  CheatSheets/npm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#57 Chore: added more vscode cheatsheet
  CheatSheets/vscode-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#59 Adding Python cheatsheet
  CheatSheets/Python-cheatsheet.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022, 📝review-pull-request

#62 Python cheatsheet update1
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#60 updated windows cheatsheet
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#63 chore: updated vscode cheatsheet
  CheatSheets/vscode-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#64 Python Cheatsheet update2
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#67 Added css-cheatsheet to the README.md file
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request

#65 Update html-cheatsheet.md
  CheatSheets/html-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request

#68 Added Shift + Alt + up/down command to vscode-CheatSheets
  CheatSheets/vscode-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 🚀ready-to-merge

#49 Added Extended Markdown Syntax
  CheatSheets/markdown-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#70 Chore: Added more Git CheatSheet for Developers
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#75 Added new command in git cheatsheet
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#72 Update git-cheatsheet.md
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#76 Python cheatsheet update 3
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#77 Added Explanation to Methods
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#83 Improvements on css cheatsheet
  CheatSheets/css-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#84 Added a new shortcut for vscode that lets you select blocks of text.
  CheatSheets/vscode-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#85 added more shortcuts in worksheet-cheatsheet.md file
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#88 Add more html tags in html-cheatsheet.md file
  CheatSheets/html-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#87 Git cheatsheets
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#86 Adding cheatsheets of Git Configuration
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#74 Add command to delete line (vscode)
  CheatSheets/html-cheatsheet.md
  CheatSheets/vscode-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#92 Update css-cheatsheet.md
  CheatSheets/css-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#89 Added Windows 11 Touchpad shortcuts
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#53 added welcome workflow
  .github/workflows/welcome.yml
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#105 Python cheatsheet update 4
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#107 add win+d shortcut
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#99 Added cheatsheet for Linux command line.
  CheatSheets/linux-cheatsheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#108 Python Cheatsheet update 5
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#110 Updated git-cheatsheet.md
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#97 Adding the <em> tag on the html-cheatsheet file
  CheatSheets/html-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#95 Added JavaScript Cheat Sheet
  CheatSheets/JavaScript-CheatSheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#114 Made some minors tweaks to the grammar and overall text formatting.
  README.md
  docs/CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#98 Added java-cheatsheet.md
  CheatSheets/java-cheatsheet.md
  README.md
Labels: question, hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#111 Docs(Update): Fixed errors
  README.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#109 Adding cheatsheets of Rewrite History
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#113 Now I have updated the changes and added some windows keyboard shortcuts.
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#115 Added conda cheatsheet
  CheatSheets/conda-cheatsheet.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#126 Python Cheatsheet update 6
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#121 Ritwikdalmia sql cheatsheets
  CheatSheets/sql-cheatsheets.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#124 Added windows snipping tool shortcut to windows-cheatsheet.md file
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#128 Created cpp-stl-cheetsheet.md
  CheatSheets/cpp-stl-cheetsheet.md
Labels: enhancement, hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#112 Few commands added
  CheatSheets/html-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, waiting-for-changes

#133 added types of variables in java
  CheatSheets/java-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#116 Adding cheatsheets of Branching & Merging
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#134 Python Cheatsheet update 7
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#129 Added Command Prompt shortcuts
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#123 Added Shortcut to take Screenshot of Selected Area
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#127 Sql cheatsheets part 3
  CheatSheets/sql-cheatsheets.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#135 added docker cheatsheet
  CheatSheets/docker-cheatsheet.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#117 refactor: update html cheatsheet
  CheatSheets/html-cheatsheet.md
Labels: duplicate, hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#137 python cheatsheet update 7
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#143 created php cheatsheet
  CheatSheets/php-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#146 One more comment about Fstrings
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#147 python Cheatsheet update 8
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#148 Final and last python cheatsheet update
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#149 Modification in CSS Style properties (adding values, making description more clear, removing fake properties)
  CheatSheets/css-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#154 Added keyboard shortcuts for Chrome DevTools CheatSheet (Mac & Windows/Linux)
  CheatSheets/chrome-devtools-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#155 Added bash_cheatsheet.md file
  CheatSheets/bash_cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#156 Create kotlin-cheatsheet.md
  CheatSheets/kotlin-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#151 Vim Editor Cheatsheet
  CheatSheets/vim-editor-cheatsheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#162 Added Some Command in Conda cheatsheet
  CheatSheets/conda-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#172 Added yarn commands in cheatSheet
  CheatSheets/yarn-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#173 Updated Windows Commands in Windows CheatSheet
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#170 Update java-cheatsheet.md
  CheatSheets/java-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#171 Update java-cheatsheet.md
  CheatSheets/java-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#164 NVM command added to cheatSheet
  CheatSheets/nvm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#159 Java cheatsheet update (Added collections framework)
  CheatSheets/java-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#157 pandas-cheatsheets
  CheatSheets/pandas-cheetsheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#103 added HTML5 input tag attributes in html cheatsheet
  CheatSheets/html-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#160 Create numpy cheatsheet
  CheatSheets/Numpy-cheatsheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#176 Updated cpp-stl-cheatsheet.md
  CheatSheets/cpp-stl-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#174 Linux commands added in CheatSheet
  CheatSheets/linux-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#136 Added AngularJS Cheatsheet
  CheatSheets/angular-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#152 Update git-cheatsheet.md with unrealted histories command
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#175 Added NPX Cheatsheet
  CheatSheets/npx-cheetsheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#180 npx-cheetsheet modified and link added
  CheatSheets/git-cheatsheet.md
  CheatSheets/npx-cheetsheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request

#184 Updated Command Cheatsheet
  CheatSheets/nvm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#183 added more commands to the linux cheatsheet
  CheatSheets/linux-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#185 added npm command for:edit, publish, rebuild packages
  CheatSheets/npm-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#178 Updated Navigation Command in VS Code Cheatsheet
  CheatSheets/vscode-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#166 add 3 array methods in javascript cheatsheet
  CheatSheets/JavaScript-CheatSheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#187 Updated Some Linux file command in linux cheatsheet
  CheatSheets/linux-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#158 Update cpp-stl-cheatsheet.md with pair sorting
  CheatSheets/cpp-stl-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#153 Update html-cheatsheet.md
  CheatSheets/html-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#94 Added few git commands to git-cheatsheet
  CheatSheets/git-cheatsheet.md
Labels: question, hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#186 Update windows-cheatsheet.md
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#145 Added Some commands in git cheatsheet
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#188 feat: add git commands #80
  CheatSheets/git-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#182 Created cmd-cheatSheet.md and added useful commands.
  CheatSheets/cmd-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#190 Update php cheatsheet
  CheatSheets/php-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#198 Fix typo in cmd-cheatsheet.md
  CheatSheets/cmd-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#200 Update Docker Cheatsheet with docker system command
  CheatSheets/docker-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#203 fixed a typo in html cheatsheet
  CheatSheets/html-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#202 Added encapsulation, abstraction, polymorphism to Java cheatsheet
  CheatSheets/java-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#201 Update pandas-cheatsheet.md
  CheatSheets/pandas-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#206 Added the shortcut to comment and uncomment the selected code
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#204 Added some more shortcuts
  CheatSheets/vscode-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#208 Added REGEX Cheatsheet and Updated README file
  CheatSheets/regex-cheatsheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#207 Add terraform cheatsheet
  CheatSheets/terraform-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#168 Created NodeJS Cheatsheet
  CheatSheets/nodeJs-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#211 Create mongodb-cheatsheet.md
  CheatSheets/mongodb-cheatsheet.md
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#210 Update in Javascript methods and added examples to use the methods
  CheatSheets/JavaScript-CheatSheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#213 Update the format for the Chrome devtools keyboard shortcut cheatsheet
  CheatSheets/chrome-devtools-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#177 Update Python cheatsheet with OpenCV
  CheatSheets/Python-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#214 Update JavaScript-CheatSheet.md
  CheatSheets/JavaScript-CheatSheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#217 mongo_db_cheatsheet_updated
  CheatSheets/mongodb-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#224 added form elements, updated forms and media
  CheatSheets/html-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#234 Sort giant list into collapsing categories
  README.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#220 Added the npx configure-react commands that help setup react app faster
  CheatSheets/configure-react-cheatsheet.md
  CheatSheets/npx-cheetsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#218 Update windows-cheatsheet.md
  CheatSheets/windows-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#231 updated nodeJs-cheatsheet
  CheatSheets/nodeJs-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#225 chrome-dev-tools cheatsheet added
  CheatSheets/chrome-devtools-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, 📝review-pull-request, 🚀ready-to-merge

#229 Added a new cheatsheet of React Js
  CheatSheets/react-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#235 Create Sklearn-cheatsheet.md
  CheatSheets/sklearn-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes

#236 added linux commands to the cheatsheet
  CheatSheets/linux-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-2022, modifications-needed, 📝review-pull-request, 🚀ready-to-merge, waiting-for-changes
